openapi: 3.0.0

info:
  version: '3.2'
  title: arcus API Documentation
  description: |
    # Introduction

    <div class="panel panel-danger">
      <div class="panel-body">
        <h4><strong>Important:</strong> We are currently working on implementing
        our Authentication method within this dynamic documentation, so that the
        'Try it out' buttons located on each endpoint work as expected. However,
        they can still be useful to show the basic Curl structure of the
        requests, to which you would need to manually add the proper
        Authentication header in order to obtain a successful response.</h4>
      </div>
    </div>

    Welcome to arcus! Here you’ll find detailed information for integrating with our API endpoints. We’ve tried to make this documentation as user-friendly and example-filled as possible, but if you have any questions, please [contact us](mailto:support@Regalii.com).

    Integration happens in six easy steps:

    1. Sign NDA
    2. Receive staging (sandbox) API keys
    3. Complete compliance approval
    4. Sign commercial contract
    5. Receive production API keys
    6. Get certified

    ---

    # Our products

    * ## xData
      Access the data of thousands of services through a unique format
    * ## xPay
      Pay bills online for any biller in the USA directly from arcus
    * ## xChange
      Update the payment information of your customers on their behalf.

    ---

    # Environments

    arcus will provide you with separate API keys for our two existing environments:

    * __Sandbox__. arcus maintains a Sandbox which allows developers to test the API using mock data. We recommend keeping in mind the following:

        * The list of billers is not in sync with the billers in production
        * Do not send real credentials to the Sandbox

      To make requests to the sandbox environment, use the following URL: `https://apix.casiregalii.com`

    * __Production__. Once you have completed all the necessary tests on the sandbox, contact us to receive your production keys.

      To make requests to the production environment, use the following URL: `https://apix.regalii.com`

    ---

    # Security

    To make requests to our endpoints, you must use the `https` protocol, regardless of the environment you're using.

    <div class="panel panel-danger">
      <div class="panel-body">
        <h4><strong>Note:</strong> For security reasons, our API doesn't support the TLS V1.0 anymore; we recommend you to use TLS v1.2 for better security.</h4>
      </div>
    </div>

    > ## Authentication

    <div class="panel panel-danger">
      <div class="panel-body">
        <h4><strong>Note:</strong> We are currently working on implementing our Authentication method within this dynamic documentation, so that you no longer have to worry about calculating the checksum and manually adding the header. In the meantime, you can try out the endpoints to receive the basic Curl structure, to which you will have to add the proper Authentication header to make a successful request.</h4>
      </div>
    </div>

    > arcus uses an api-key and a secret-key for authentication that we generate and will provide to you, one for each environment.

    > arcus expects for the api-key to be included in all API requests to the server in the ‘Authorization’ header, combined with a checksum which we will describe later on:

    > __Authorization:__ `APIAuth <your-api-key>:<checksum>`

    * ### Calculating the Checksum

        1. A checksum string needs to be created first by using your HTTP headers containing the `Content-Type`, `Content-MD5`, `Endpoint` and today's `Timestamp`.

            The checksum string is computed as follows:

            checksum_string = `content-type`,`content-md5`,`endpoint`,`timestamp`

              - __Note:__ The ‘Endpoint’ is simply the URL you are sending the request to, excluding the server and including the parameters. For instance, if you
              want to obtain a bill's data by requesting a get to `https://apix.casiregalii.com/bills/1`, your
              checksum string should look like this:
              `application/json,,/bills/1,Wed, 10 Jan 2017 16:53:15 GMT`
              - __Note:__ Please notice the timestamp format. In UNIX-based systems you could obtain it by running: <b>echo \`date -Ru | sed 's/+0000/GMT/'`</b> in your terminal.

        2. The checksum string is then used to create the checksum, which is a Base64 SHA1 HMAC string encoded using your private secret key.

        3. For testing, verify that if you pass `application/json,,/account,Wed, 02 Nov 2016 17:26:52 GMT` to your checksum function and use `verify-secret` as secret key, it should return `nLet/JEZG9CRXHScwaQ/na4vsKQ=`. See checksum verification [example](https://gist.github.com/dagosi/c2e7db228a9c15e2f5bcdccd7a056183).

            How to create a checksum in [Bash](https://gist.github.com/dagosi/d85979e364af745750a9dff8c8c5a949):

            ```
            CURRENT_DATE=`date -Ru | sed 's/+0000/GMT/'`
            CHECKSUM=$(echo -n "application/json,,/account,$CURRENT_DATE" \
              | openssl dgst -sha1 -binary -hmac "your-secret-key" \
              | base64)
            ```

    * ### How to use the Checksum

      Now that you have a checksum, you can add it to your headers using the `Authorization` header as we previously mentioned. As an example, let’s assume that your api-key is `f0253d2a6a76ed12499e7878d7803ffb` and that your checksum is `nLet/JEZG9CRXHScwaQ/na4vsKQ=`. Now, you can add this header to your request.

      `-H Authorization: APIAuth f0253d2a6a76ed12499e7878d7803ffb:nLet/JEZG9CRXHScwaQ/na4vsKQ=`

    ___

    # Webhooks

    arcus offers webhooks which can be used to notify you when there are updates to a bill or
    transaction.

    You can set up a webhook URL with arcus by contacting us.

    * ## Bills' Webhook
      Webhooks return the same data offered in the bill status.

      * The bill finishes updating and now requires password entry (error 420); waiting; or has data ready since updated
      * A long-running fetch has completed
      * The bill has been re-run by arcus due to an earlier error or outage
      * It is the client's responsibility to trigger bills to refresh under normal operation.

    # Tools for Testing

    It is recommended that you first test a couple of endpoints and get familiarized with their responses. This will give you an idea of how to properly construct requests in your application (and save you coding time).

    You can do so by using the following dynamic sections of this documentation.

    Additionally, you can use any of the following tools:

      * [Paw](https://paw.cloud/)
      * [Postman](https://www.getpostman.com/)
      * [Insomnia](https://insomnia.rest/)

    # Language bindings

      We have created libraries in multiple languages that will make it easier for you to use our API:

      * [Ruby](https://github.com/regalii/regaliator)
      * [Java](https://github.com/regalii/regaliator_java)
      * [Node.JS](https://github.com/regalii/regaliator_node)
      * [Python](https://github.com/regalii/regaliator_python)
      * [PHP](https://github.com/regalii/regaliator_php)

    <div class="panel panel-danger">
      <div class="panel-body">
        <h4><strong>REMEMBER:</strong> Never send real credentials to the Sandbox.</h4>
      </div>
    </div>

    # Errors

    Responses will use standard HTTP error codes to convey basic error status information.

    Unless you obtain a successful response (code 200), you may encounter any of the following:

    <table>
      <tr>
        <th>Error Code</th>
        <th>Meaning</th>
      </tr>
      <tr>
        <td>400</td>
        <td>Bad Request</td>
      </tr>
      <tr>
        <td>401</td>
        <td>Unauthorized -- Your API key or checksum is wrong</td>
      </tr>
      <tr>
        <td>403</td>
        <td>Forbidden -- You are not authorized to access the resource requested</td>
      </tr>
      <tr>
        <td>404</td>
        <td>Not Found -- The specified resource could not be found</td>
      </tr>
      <tr>
        <td>429</td>
        <td>Too Many Requests -- You're sending too many requests! Slow down!</td>
      </tr>
      <tr>
        <td>500</td>
        <td>Internal Server Error -- We had a problem with our server. Try again later.</td>
      </tr>
      <tr>
        <td>503</td>
        <td>Service Unavailable -- Please try again later.</td>
      </tr>
    </table>

servers:
  - url: https://apix.casiregalii.com
    description: Sandbox, Mock Credentials; Mock Data
  - url: https://apix.regalii.com
    description: Production, Real Credentials; Real Data

tags:
  - name: Common
    description: Common endpoints
  - name: xData
    description: Access to xData documentation
  - name: xPay
    description: Access to xPay documentation
  - name: xChange
    description: Access to xChange documentation

paths:
  /account:
    get:
      tags:
        - Common
      summary: Returns the properties of your arcus account.
      operationId: getAccount
      description: >-
        This endpoint returns the properties of your arcus account, which
        include the name of your company, the currency you work with and, in
        case you're an xPay client, the current balance you have available to
        make transactions.

      parameters:
        - $ref: '#/components/parameters/DateParam'
        - $ref: '#/components/parameters/ContentMD5Param'
      responses:
        200:
          description: successful response
          content:
            application/vnd.regalii.v3.2+json:
              schema:
                type: object
                properties:
                  name:
                    type: string
                    description: the name of your company
                  balance:
                    type: number
                    description: the current balance your company has available
                      to make transactions
                  minimum_balance:
                    type: number
                    description: "[deprecated]"
                  currency:
                    type: string
                    description: the balance's currency
                example:
                  name: ACME Company
                  balance: 7000.00
                  minimum_balance: 5000.00
                  currency: USD
  /billers:
    get:
      tags:
        - Common
      summary: Provides the current list of billers and their associated
        properties.
      operationId: getBillersCredentials
      description: |
        This endpoint provides the current list of billers and their associated
        properties.
        To ensure that your end users are able to leverage the enhancements that
        we make over time, you are required to cache the full list of billers
        and update it on a weekly basis.
      parameters:
        - in: path
          name: page
          required: true
          description: page index for returned information.
          schema:
            type: integer
        - $ref: '#/components/parameters/DateParam'
        - $ref: '#/components/parameters/ContentMD5Param'
      responses:
        200:
          description: successful response
          content:
            application/vnd.regalii.v3.2+json:
              schema:
                type: array
                title: billers
                properties:
                  type:
                    type: string
                    description: biller
                  id:
                    type: integer
                    description: the ID of the biller [deprecated]
                  uuid:
                    type: string
                    description: the UUID of the biller
                  name:
                    type: string
                    description: the name of the biller
                  country:
                    type: string
                    description: country of the biller
                  currency:
                    type: string
                    description: currency of the biller
                  biller_type:
                    type: string
                    description: is the type of biller
                  bill_type:
                    type: string
                    description: the type of bill, that can be for example water, internet, cable and so on
                  required_parameters:
                    type: array
                    description: the login and password required parameters
                    items:
                      type: string
                  returned_parameters:
                    description: the returned parameters by the bill
                    type: array
                    items:
                      type: string
                  can_migrate:
                    description: can use xChange
                    type: boolean
                  charge_user:
                    description: can charge user
                    type: boolean
                  has_xdata:
                    description: can use xData
                    type: boolean
                example:
                  type: biller
                  id: 6510
                  uuid: 3bc572a9-cb55-4aea-80aa-40b058d26673
                  name: Con Edison
                  country: US
                  currency: USD
                  biller_type: Electricity
                  bill_type: credentials
                  required_parameters: [login,password]
                  returned_parameters: [balance,due_date,account_number,name_on_account,xdata]
                  can_migrate: false
                  charge_user: true
                  has_xdata: false
  /bills:
    post:
      tags:
        - xData
      summary: Creates a bill for a specific biller
        identifier
      operationId: createBills
      description: |
        This endpoint creates a bill for a specific biller.

        When you send the credentials and biller_id to create a bill, the bill
        object is created and we then attempt to fetch the bill from the biller.
        Thus no matter what happens (MFA, wrong credentials, biller down, etc),
        the bill object is created.

        Take into account that the request may take up to 59 seconds to return.

        If an error or MFA is returned, update the bill to resolve the issue.

        ## Handling Multi-factor Authentication

        Some billers require more than just a username/password to log in. In
        those situations, arcus will associate one or more MFA challenges with a
        bill. An MFA challenge can be a verification code sent to a phone, a
        secret question, an image, a list of images to choose from, or different
        choices which only the end user would know the answer to. When arcus
        refreshes a bill, it will be set into a status of waiting, which means
        that the customer must answer a challenge. Go to `PATCH /bills/{id}` to
        see how to reply to a challenge.

        ## For testing purposes
        The Sandbox accepts any credentials (we remind you never to send real
        credentials). However, you can use the following login suffixes when
        creating a bill to force a certain response (just the @{state}.ii is the
        required part; email can be anything).

          <table class="table table-hover">
             <tr>
              <td><strong>Login</strong></td>
              <td><strong>Status</strong></td>
              <td><strong>Error Code</strong></td>
            </tr>
             <tr>
              <td>email@fetching.ii</td>
              <td>updating</td>
              <td></td>
            </tr>
             <tr>
              <td>email@mfa_code.ii</td>
              <td>waiting</td>
              <td></td>
            </tr>
             <tr>
              <td>email@mfa_question.ii</td>
              <td>waiting</td>
              <td></td>
            </tr>
            <tr>
              <td>email@mfa_choice.ii</td>
              <td>waiting</td>
              <td></td>
            </tr>
            <tr>
              <td>email@mfa_image.ii</td>
              <td>waiting</td>
              <td></td>
            </tr>
             <tr>
              <td>email@mfa_image_choice.ii</td>
              <td>waiting</td>
              <td></td>
            </tr>
            <tr>
              <td>email@successful.ii</td>
              <td>updated</td>
              <td></td>
            </tr>
            <tr>
              <td>email@unavailable.ii</td>
              <td></td>
              <td>R122</td>
            </tr>
            <tr>
              <td>email@input.ii</td>
              <td></td>
              <td>R121</td>
            </tr>
            <tr>
              <td>email@credentials.ii</td>
              <td></td>
              <td>R120</td>
            </tr>
            <tr>
              <td>email@exception.ii</td>
              <td></td>
              <td>R121</td>
            </tr>
             <tr>
              <td>email@timeout.ii</td>
              <td></td>
              <td>R121</td>
            </tr>
          </table>

      requestBody:
        description: Within the request body the parameters sent are a biller_id, login and password
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                biller_id:
                  type: string
                  description: The ID of the biller.
                  example: "0282369b-acd1-4e44-a894-c2a10ea5f8e3"
                login:
                  type: string
                  description: The account login.
                  example: "jdoe@successful.ii"
                password:
                  type: string
                  description: The account password
                  example: "HeLl0o1!"
              required:
                - biller_id
                - login
                - password
      parameters:
        - $ref: '#/components/parameters/DateParam'
        - $ref: '#/components/parameters/ContentMD5Param'
      responses:
        200:
          description: successful response
          content:
            application/vnd.regalii.v3.2+json:
              schema:
                $ref: '#/components/schemas/Bill'
    get:
      tags:
        - xData
      summary: Retrieves all your bills
      operationId: getBills
      description: |
        This endpoint retrieves all your bills.
      parameters:
        - in: query
          name: page
          required: false
          description: If set, it allows you to display any page of bills.
          schema:
            type: integer
        - in: query
          name: q[created_at_gteq]
          schema:
            type: string
            items:
              type: string
              format: date-time
          required: false
          description: If set, it’ll return results after the specified timestamp.
        - in: query
          name: q[created_at_lteq]
          required: false
          description: If set, it’ll return results before the specified timestamp.
          schema:
            type: string
            items:
              type: string
              format: date-time
        - in: query
          name: q[id_in][]
          required: false
          description: If set, it’ll return the bills for the specified bill ids.
          schema:
            type: array
            items:
              type: string
              items:
                type: string
        - $ref: '#/components/parameters/DateParam'
        - $ref: '#/components/parameters/ContentMD5Param'
      responses:
        200:
          description: successful response
          content:
            application/vnd.regalii.v3.2+json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Bill'
                example:
                  bills:
                    - type: bill
                      id: 674124
                      uuid: c5482bbe-0f46-4e30-b660-3b1bb0ea773f
                      biller_id: 6510
                      biller_uuid: b44f5c1c-a6b7-4688-8311-080512ca4f1e
                      account_number: 87249256
                      name_on_account: Rita Sporer
                      due_date: '2017-01-29T05:00:00Z'
                      balance: 62.38
                      balance_currency: USD
                      balance_updated_at: '2017-01-17T19:57:56Z'
                      error_code: null
                      error_message: null
                      status: linked
                      migrated_at: null
                      mfa_challenges: []
                    - type: bill
                      id: 674125
                      uuid: c5482bbe-0f46-4e30-b660-3b1bb0ea773f
                      biller_id: 1
                      biller_uuid: b44f5c1c-a6b7-4688-8311-080512ca4f1e
                      account_number: 1234567
                      name_on_account: Jose Bautista
                      due_date: null
                      balance: 400
                      balance_currency: RD
                      balance_updated_at: '2017-01-17T21:47:19Z'
                      error_code: null
                      error_message: null
                      status: linked
                      migrated_at: null
                      mfa_challenges: []
  /bills/{id}:
    get:
      tags:
        - xData
      summary: Retrieves a specific bill’s cached data
      operationId: getBill
      description: |
        This endpoint retrieves a specific bill’s cached data. To pull fresh
        data from a biller see `POST /bills/{id}/refresh`
      parameters:
        - name: id
          in: path
          description: ID of bill to return
          required: true
          schema:
            type: integer
        - $ref: '#/components/parameters/DateParam'
        - $ref: '#/components/parameters/ContentMD5Param'
      responses:
        200:
          description: successful response
          content:
            application/vnd.regalii.v3.2+json:
              schema:
                $ref: '#/components/schemas/Bill'
    patch:
      tags:
        - xData
      summary: Allows you to update a specific bill's credentials and/or answer
        MFA challenges
      description: |
        This endpoint allows you to update a specific bill's credentials and/or
        answer MFA challenges.

        ## Replying to MFA Challenges

        In order to answer MFA challenges, you must provide the credentials and
        an array named 'mfa_challenges', containing one or more objects
        (depending on how many challenges the biller provided) with the
        following attributes: id, type and response. Make sure that the id and
        type match the mfa_challenge. For more detailed information refer to the
        MFA_Response Model.

        ### Bill's status changes

        * Once the challenge has been answered, arcus will be able to update the
          bill's balance. The bill's status will be set to 'updating'.
        * Once the bill balance has been updated, the bill's status will be set
          to 'updated'.
        * If the response of an mfa_challenge is incorrect OR the response is
          provided after `expires_at` time, then an error will be given and the
          bill's status will be set to 'failed'.

      operationId: updateBill

      parameters:
        - name: id
          in: path
          description: ID of bill to return
          required: true
          schema:
            type: integer
        - $ref: '#/components/parameters/DateParam'
        - $ref: '#/components/parameters/ContentMD5Param'
      requestBody:
        description: Within the request body the parameters sent are a login, password and
          an array of mfa_challenges objects
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                login:
                  type: string
                  description: The username/email address/identifier credential
                password:
                  type: string
                  description: The password credential
                mfa_challenges:
                  type: array
                  description: Challenges information
                  items:
                    $ref: '#/components/schemas/MFA_Response'
              required:
                  - login
                  - password
      responses:
        200:
          description: successful response
          content:
            application/vnd.regalii.v3.2+json:
              schema:
                $ref: '#/components/schemas/Bill'
    delete:
      tags:
        - xData
      summary: Deletes a specific bill
      description: This endpoint deletes a specific bill
      operationId: deleteBill
      parameters:
        - name: id
          in: path
          description: ID of bill to return
          required: true
          schema:
            type: integer
        - $ref: '#/components/parameters/DateParam'
        - $ref: '#/components/parameters/ContentMD5Param'
      responses:
        200:
          description: successful response
          content:
            application/vnd.regalii.v3.2+json:
              schema:
                $ref: '#/components/schemas/Bill'
  /bills/{id}/refresh:
    post:
      tags:
        - xData
      summary: Refreshes a specific bill by polling the biller
      description: |
        This endpoint refreshes a specific bill by polling the biller. It
        responds with the same structure as `POST /bills`.
      operationId: refreshBill
      parameters:
        - name: id
          in: path
          description: ID of bill to return
          required: true
          schema:
            type: integer
        - $ref: '#/components/parameters/DateParam'
        - $ref: '#/components/parameters/ContentMD5Param'
      responses:
        200:
          description: successful response
          content:
            application/vnd.regalii.v3.2+json:
              schema:
                $ref: '#/components/schemas/Bill'
  /bills/bulk_refresh:
    post:
      tags:
        - xData
      summary: Receives an array of bill ids and refreshes them
      description: |
        This endpoint receives an array of bill ids as a parameter and refreshes
        them. Updated bills can be eventually pulled by passing id_in to the
        `GET /bills` endpoint.

      operationId: bulk_refreshBill
      parameters:
        - $ref: '#/components/parameters/DateParam'
        - $ref: '#/components/parameters/ContentMD5Param'
      requestBody:
        description: Within the request body the parameters sent are a biller_id, login and password
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                bill_ids:
                  type: array
                  description: Array of bill ids.
                  items:
                    type: string
              required:
                - bill_ids
      responses:
        200:
          description: successful response
          content:
            application/vnd.regalii.v3.2+json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                example:
                  message: Refresh in progress for 3 bills
  /rpps_billers:
    get:
      tags:
        - xPay
      summary: Provides the list of xPay billers
      description: |
        This endpoint provides the list of xPay billers.
      operationId: getRppsBillers
      parameters:
        - $ref: '#/components/parameters/DateParam'
        - $ref: '#/components/parameters/ContentMD5Param'
        - name: q[biller_type_eq]
          in: query
          required: false
          description: Only returns rpps billers of that biller type
          schema:
            type: string
        - name: q[name_eq]
          in: query
          required: false
          description: Only returns rpps billers of that biller name
          schema:
            type: string
        - name: q[country_eq]
          in: query
          required: false
          description: Only returns rpps billers of that country
          schema:
            type: string
      responses:
        200:
          description: successful response
          content:
            application/vnd.regalii.v3.2+json:
              schema:
                type: object
                properties:
                  id:
                    description: Id of the rpps biller
                    type: integer
                  name:
                    description: name of the rpps biller
                    type: integer
                  biller_type:
                    description: the type of biller
                    type: string
                  biller_class:
                    description: the biller class belongs
                    type: string
                  country:
                    description: the country that the rpps biller belongs
                    type: string
                  state:
                    description: the state that the rpps biller belongs
                    type: string
                  territory_code:
                    description: the territory code that the rpps biller belongs
                    type: string
                  currency:
                    description: the currency supported by the rpps biller
                    type: string
                  address:
                    description: the address of the rpps biller
                    type: array
                  masks:
                    description: the masks of the rpps biller
                    type: array
                example:
                  rpps_billers:
                    - id: 692b45ea-7369-4232-bdd6-2bd662fe1ebd
                      name: 1000 Granville Homeowners Association
                      biller_type: Core
                      biller_class: Homeowners Association
                      country: USA
                      state: null
                      territory_code: National
                      currency: USD
                      addresses:
                        - city: San Francisco
                          state: CA
                          country: USA
                          address1: PO Box 45463
                          address2: null
                          eff_date: 2010-07-26
                          external_id: 67942
                          postal_code: 94145-0463
                          address_type: Standard
                      masks:
                        - length: 7
                          eff_date: 2010-07-20
                          exception: false
                          external_id: 343033
                          mask_format: ####-##
                          descriptions: []
                        - length: 8
                          eff_date: 2010-07-20
                          exception: false
                          external_id: 343034
                          mask_format: ####-###
                          descriptions: []
                        - length: 4
                          eff_date: 2010-07-20
                          exception: false
                          external_id: 343035
                          mask_format: ####
                          descriptions: []
                        - length: 3
                          eff_date: 2010-07-20
                          exception: false
                          external_id: 343036
                          mask_format: ###
                          descriptions: []
                        - length: 7
                          eff_date: 2010-07-20
                          exception: false
                          external_id: 343037
                          mask_format: ###-###
                          descriptions: []
                        - length: 8
                          eff_date: 2010-07-20
                          exception: false
                          external_id: 343038
                          mask_format: ###-###@
                          descriptions: []
  /transactions:
    post:
      tags:
        - xPay
      summary: Creates a new transaction
      description: |
        With this endpoint you can create a new transaction by passing an xPay
        Biller ID and information about the payment and the end user who is
        making the payment (see parameters below).
        <br/><br/>
        Once the transactions are created in arcus’ system, it takes 2-3 days to
        process the transaction. After that time, the transaction’s status will
        be updated. You can always check the transaction's status by making a
        request to the `GET /transactions/{id}` endpoint.
      operationId: postTransactions
      parameters:
        - $ref: '#/components/parameters/DateParam'
        - $ref: '#/components/parameters/ContentMD5Param'
      requestBody:
        description: Within the request body the required parameters to be sent are an `account_number`, `amount`, `currency`, `rpps_biller_id`, `payer_born_on`, `first_name`, `last_name` and an `address` object with required information for `city` and `state`.
         <br/><br/>
         You have to make sure the `account_number` matches one of the masks' `mask_format` of the xPay Biller.
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - account_number
                - amount
                - currency
                - rpps_biller_id
                - payer_born_on
                - first_name
                - last_name
                - address
              properties:
                account_number:
                  type: string
                  description: Account number where the payment is directed to.
                  example: "1234-56"
                amount:
                  type: integer
                  description: Amount to pay
                  example: "2000.0"
                currency:
                  type: string
                  description: Amount's currency
                  example: "USD"
                rpps_biller_id:
                  type: string
                  description: xPay Biller identifier
                  example: "692b45ea-7369-4232-bdd6-2bd662fe1ebd"
                phone_number:
                  type: string
                  description: Phone number of the person who makes the payment
                  example: "(714) 202-5081"
                client_number:
                  type: string
                  description: Client number of the person who makes the payment
                  example: "805-612-0442"
                payer_born_on:
                  type: string
                  format: date
                  description: Date of birth of the payer of the transaction
                  example: "1983-09-03"
                first_name:
                  type: string
                  description: First name of the person who makes the payment
                  example: "John"
                last_name:
                  type: string
                  description: Last name of the person who makes the payment
                  example: "Doe"
                address:
                  type: object
                  description: Address of the person who makes the payment.
                  required:
                    - city
                    - state
                  properties:
                    street:
                      type: string
                      example: "351 W 14th St Apt L"
                    zip_code:
                      type: string
                      example: "10014"
                    city:
                      type: string
                      example: "New York"
                    state:
                      type: string
                      example: "NY"
      responses:
        200:
          description: successful response
          content:
            application/vnd.regalii.v3.2+json:
              schema:
                $ref: '#/components/schemas/Transaction'

    get:
      tags:
        - xPay
      description: |
        This endpoint returns the list of transactions that arcus has processed for you.
      summary: Returns the list of transactions that arcus has processed for you
      operationId: getAllTransactions
      parameters:
        - in: query
          name: page
          required: false
          description: Allows you to obtain a specific page of the transactions’ list
          schema:
            type: integer
        - in: query
          name: q[created_at_gteq]
          required: false
          description: Returns those transactions that were created after the timestamp provided
          schema:
            type: string
            format: date-time
        - in: query
          name: q[created_at_lteq]
          required: false
          description: Returns those transactions that were created before the timestamp provided
          schema:
            type: string
            format: date-time
        - in: query
          name: q[biller_id_eq]
          required: false
          description: Returns the transactions of a specific biller
          schema:
            type: string
        - in: query
          name: q[bill_id_eq]
          required: false
          description: Query transactions using the external_id you supplied
          schema:
            type: string
        - in: query
          name: q[biller_id_in][]
          required: false
          description: Returns the transactions of the billers whose ids are provided
          schema:
            type: array
            items:
              type: string
        - in: query
          name: q[bill_id_in][]
          required: false
          description: Returns the transactions of the bills whose ids are provided
          schema:
            type: array
            items:
              type: string
        - $ref: '#/components/parameters/DateParam'
        - $ref: '#/components/parameters/ContentMD5Param'
      responses:
        200:
          description: successful response
          content:
            application/vnd.regalii.v3.2+json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Transaction'
                example:
                  transactions:
                    - id: 9fe8bf62-d78b-462c-9195-14977420bbeb
                      status: initialized
                      bill_id: null
                      account_number: 12345
                      currency: USD
                      amount: 2000.0
                      created_at: '2018-04-06T14:49:12.830Z'
                      updated_at: '2018-04-06T14:49:12.830Z'
                      error_code: null
                      error_message: null
  /transactions/{id}:
    get:
      tags:
        - xPay
      summary: Returns the details of a specific transaction
      description: |
        This endpoint returns the details of a specific transaction. If the
        payment was successful, you would see the transaction status is
        __linked__. If there is any problem with the payment, you would see the
        __error_code__ and __error_message__ in the transaction’s response. The
        possible values for transaction’s status are `initialized`, `pending`,
        `linked`, `confirmed` and `rejected`.
      operationId: getTransactions
      parameters:
        - in: path
          name: id
          required: true
          description: Id of the transaction
          schema:
            type: integer
        - $ref: '#/components/parameters/DateParam'
        - $ref: '#/components/parameters/ContentMD5Param'
      responses:
        200:
          description: successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Transaction'

    delete:
      tags:
        - xPay
      summary: Deletes a specific transaction
      description: |
        Deletes the transaction that corresponds to the `id` sent. It’s only
        possible to delete a transaction if the processing of the transaction's
        payment hasn’t started, i.e., if it’s still in the __initialized__
        state. If you make a request to delete an already processing
        transaction, then you would get an __unprocessable_entity__ HTTP
        response.
      operationId: getTransactions
      parameters:
        - in: path
          name: id
          required: true
          description: Id of the transaction
          schema:
            type: integer
        - $ref: '#/components/parameters/DateParam'
        - $ref: '#/components/parameters/ContentMD5Param'
      responses:
        200:
          description: successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Transaction'

  /migrations:
    post:
      tags:
        - xChange
      summary: Replaces the payment method on the biller’s website
      description: |
        Use this endpoint to replace the payment method on the biller’s website.
      operationId: postMigrations
      parameters:
        - $ref: '#/components/parameters/DateParam'
        - $ref: '#/components/parameters/ContentMD5Param'
      requestBody:
        description: Within the request body the parameters sent are `biller_id`, `login` for the account, `password`, the `name`, `last name`, `country`, `card number`, `brand of the card`, `expiry year`, `expiry month`, `address`, `city`, `state`, `zipcode`, card `type` if it is credit or debit and the `cvv` of three or four numbers
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - biller_id
                - login
                - password
                - cc_first_name
                - cc_last_name
                - cc_country
                - cc_number
                - cc_brand
                - cc_expiry_year
                - cc_address
                - cc_city
                - cc_state
                - cc_type
                - cc_zip
                - cc_security_code
                - cc_expiry_month
              properties:
                biller_id:
                  type: string
                  description: The ID of the biller.
                  example: "6ab564f9-4e9d-4b03-96d6-dd9f2c39ec53"
                login:
                  type: string
                  description: The username/email address/identifier credential
                  example: "someone@gmail.com"
                password:
                  type: string
                  description: The password credential
                  example: "Pwd123!"
                cc_first_name:
                  type: string
                  description: End user’s first name
                  example: "Elon"
                cc_last_name:
                  type: string
                  description: End user’s last name
                  example: "Musk"
                cc_country:
                  type: string
                  description: Country where card number was issued (US only for the time being)
                  example: "US"
                cc_number:
                  type: string
                  description: Card number
                  example: "5221740002389461"
                cc_brand:
                  type: string
                  description: mastercard/visa/american_express
                  example: "visa"
                cc_expiry_year:
                  type: string
                  description: 4 number digit
                  example: "2021"
                cc_address:
                  type: string
                  description: Street name and number
                  example: "351 W 14th St Apt L"
                cc_city:
                  type: string
                  description: City
                  example: "New York"
                cc_state:
                  type: string
                  description: Two letter abbreviation of a US state
                  example: "NY"
                cc_type:
                  type: string
                  description: credit/debit
                  example: "credit"
                cc_zip:
                  type: string
                  description: Address’ zipcode
                  example: "10014"
                cc_security_code:
                  type: string
                  description: Card’s security code (3 or 4 digit number)
                  example: "123"
                cc_expiry_month:
                  type: string
                  description: Card’s expiry month (2 digit number)
                  example: "02"

      responses:
        200:
          description: successful response
          content:
            application/vnd.regalii.v3.2+json:
              schema:
                $ref: '#/components/schemas/Migration'
    get:
      tags:
        - xChange
      summary: Gets all your attempted migrations
      description: |
        This endpoint is used to get all your attempted migrations.
      operationId: getMigrations
      parameters:
        - name: page
          in: query
          description: If set, it allows you to display any page of the migrations’ list
          required: false
          schema:
            type: integer
        - $ref: '#/components/parameters/DateParam'
        - $ref: '#/components/parameters/ContentMD5Param'
      responses:
        200:
          description: successful response
          content:
            application/vnd.regalii.v3.2+json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Migration'
                example:
                  migrations:
                    - error_code: null
                      error_message: null
                      id: de2a19ff-91d1-4c45-b6c4-cb4abfaa4077
                      status: updating
                      requested_at: 2018-04-06T18:18:36.144Z
                      migrated_at: null
                    - error_code: null
                      error_message: null
                      id: d13efe0e-d79c-4770-9a56-1487504ce4b0
                      status: updating
                      requested_at: 2018-04-06T18:16:00.033Z
                      migrated_at: null
  /migrations/{id}:
    get:
      tags:
        - xChange
      summary: Gets the last migration attempt of a bill
      description: >-
        This endpoint gets the last migration attempt of a bill.
      operationId: getMigration
      parameters:
        - name: id
          in: path
          description: ID of bill to return
          required: true
          schema:
            type: integer
        - $ref: '#/components/parameters/DateParam'
        - $ref: '#/components/parameters/ContentMD5Param'
      responses:
        200:
          description: successful response
          content:
            application/vnd.regalii.v3.2+json:
              schema:
                $ref: '#/components/schemas/Migration'

    patch:
      tags:
        - xChange
      summary: Allows the resolution of an MFA challenge
      description: |
        This endpoint allows the resolution of an MFA challenge associated with
        the bill whose migration was requested.
      operationId: updateMigration
      parameters:
        - name: id
          in: path
          description: ID of bill to return
          required: true
          schema:
            type: integer
        - $ref: '#/components/parameters/DateParam'
        - $ref: '#/components/parameters/ContentMD5Param'
      requestBody:
        description: Within the request body the parameters sent are login and password
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                login:
                  type: string
                  description: The username/email address/identifier credential
                password:
                  type: string
                  description: The password credential
                mfa_challenges:
                  type: array
                  description: Challenges information
                  items:
                    $ref: '#/components/schemas/MFA_Response'
              required:
                - login
                - password
      responses:
        200:
          description: successful response
          content:
            application/vnd.regalii.v3.2+json:
              schema:
                $ref: '#/components/schemas/Migration'

components:
  parameters:
    DateParam:
      name: Date
      in: header
      description: Today's date (e.g. Wed, 11 Apr 2018 17:34:23 GMT)
      required: true
      schema:
        type: string
        format: date-time
    ContentMD5Param:
      name: Content-MD5
      in: header
      description: Content-MD5
      required: false
      schema:
        type: string
  schemas:
    Transaction:
      type: object
      properties:
        id:
          description: the generated transaction id
          type: integer
        status:
          description: the status of the transaction
          type: string
        bill_id:
          description: related bill with transaction
          type: string
        account_number:
          description: related account number with the transaction
          type: string
        currency:
          description: currency for the transaction
          type: string
        amount:
          description: amount of the transaction
          type: number
        created_at:
          description: timestamp of the transaction
          type: string
        updated_at:
          description: timestamp of the transaction update
          type: string
        error_code:
          description: the error code in the case of get one
          type: string
        error_message:
          description: the error message associated to error code in the case of get one
          type: string

      example:
        id: be42c413-fcce-4857-b6fa-374228e33912
        status: initialized
        bill_id: null
        account_number: 1234-56
        currency: USD
        amount: 2000.0
        created_at: '2018-04-06T15:41:52.846Z'
        updated_at: '2018-04-06T15:41:52.846Z'
        error_code: null
        error_message: null

    Migration:
      type: object
      properties:
        error_code:
          description: the error code in the case of get one
          type: string
        error_message:
          description: the error message associated to error code in the case of get one
          type: string
        id:
          description: id of the generated migration
          type: string
        status:
          description: status of the generated migration
          type: string
        requested_at:
          description: timestamp of the requested migration
          type: string
        migrated_at:
          description: timestamp of the successful migration
          type: string
      example:
        error_code: null
        error_message: null
        id: de2a19ff-91d1-4c45-b6c4-cb4abfaa4077
        status: updating
        requested_at: '2018-04-06T18:18:36.144Z'
        migrated_at: null

    Bill:
      type: object
      properties:
        type:
          type: string
          description: bill
        id:
          type: integer
          description: the ID of the bill [deprecated]
        uuid:
          type: string
          description: the UUID of the bill
        biller_id:
          type: integer
          description: the ID of the biller [deprecated]
        biller_uuid:
          type: string
          description: the UUID of the biller
        account_number:
          type: string
          description: the bills account number
        name_on_account:
          type: string
          description: the name asociated with the accoun number
        due_date:
          type: string
          description: the deadline to pay the bill
          format: date
        balance:
          type: number
          description: the returned balance
        balance_currency:
          type: string
          description: the bills currency
        balance_updated_at:
          type: string
          description: the date of last balance update
          format: date-time
        error_code:
          type: string
          description: the error code in the case of get one
        error_message:
          type: string
          description: the error message associated to error code in the case of get one
        status:
          type: string
          description: one of the different posible status associated to the bill
        migrated_at:
          type: string
          format: date-time
        mfa_challenges:
          description: params for multi-factor authentication challenge
          type: array
          items:
            oneOf:
              - $ref: '#/components/schemas/MFA_Challenge_Question'
              - $ref: '#/components/schemas/MFA_Challenge_Code'
              - $ref: '#/components/schemas/MFA_Challenge_Image'
              - $ref: '#/components/schemas/MFA_Challenge_Image_Choices'
              - $ref: '#/components/schemas/MFA_Challenge_Choices'
      example:
        type: bill
        id: 674117
        uuid: c5482bbe-0f46-4e30-b660-3b1bb0ea773f
        biller_id: 6535
        biller_uuid: ce56e8a6-6162-423f-8dc6-e0ccab5ef70b
        account_number: 4222422244
        name_on_account: Jose Bautista
        due_date: '2016-11-30'
        balance: 56.43
        balance_currency: USD
        balance_updated_at: '2017-01-16T20:12:58Z'
        error_code: null
        error_message: null
        status: linked
        migrated_at: null
        mfa_challenges: []

    MFA_Response:
      type: object
      required:
        - id
        - type
        - response
      properties:
        id:
          type: string
          description: The ID or UUID of the challenge that is being answered
        type:
          type: string
          description: The type of challenge (question, code, image, image_choice)
        response:
          type: string
          description: In the case of type 'code' or 'question', the answer to the challenge. In the case of type 'image', the size of the image. In the case of 'image_choice' and '?', the ID (index) of the correct choice.

    MFA_Challenge:
      description: Shared information of MFA Challenges
      type: object
      required:
        - type
        - id
        - uuid
        - expires_at
      properties:
        type:
          type: string
          description: The type of challenge (question, code, image, image_choice)
        id:
          type: integer
          description: The ID of the challenge [deprecated]
        uuid:
          type: string
          description: The UUID of the challenge
        expires_at:
          type: string
          format: date-time
          description: The delay of expiration; after this date the answer will be rejected. It can be null

    MFA_Challenge_Question:
      description: Structure of an MFA Challenge of type 'question'. Secret questions are often asked in addition to a user's password.
      allOf:
        - $ref: '#/components/schemas/MFA_Challenge'
        - type: object
          required:
            - prompt
          properties:
            prompt:
              type: string
              description: The question to show to the owner of the account
              example: What is 4 + 4?

    MFA_Challenge_Code:
      description: Structure of an MFA Challenge of type 'code'. Verification codes are sometimes sent to a customer’s mobile phone before they are able to log in. Verification codes cannot be re-used.
      allOf:
        - $ref: '#/components/schemas/MFA_Challenge'
        - type: object
          required:
            - prompt
          properties:
            prompt:
              type: string
              description: The instructions to show to the owner of the account
              example: Please provide the code sent on your phone.

    MFA_Challenge_Image:
      description: Structure of an MFA Challenge of type 'image'
      allOf:
        - $ref: '#/components/schemas/MFA_Challenge'
        - type: object
          required:
            - prompt
          properties:
            prompt:
              type: object
              properties:
                type:
                  type: string
                  description: "The type of the image: url or uri"
                value:
                  type: string
                  description: The URL of the image for url or the content of the image for uri
                  example: http://via.placeholder.com/350x150

    MFA_Challenge_Image_Choices:
      description: Structure of an MFA Challenge of type 'image_choice'
      allOf:
        - $ref: '#/components/schemas/MFA_Challenge'
        - type: object
          required:
            - prompt
          properties:
            prompt:
              type: array
              description: An array of images
              items:
                type: object
                properties:
                  id:
                    type: integer
                    description: The ID of the option (basically the index of the array)
                  type:
                    type: string
                    description: "The type of the image: url or uri"
                  value:
                    type: string
                    description: The URL of the image for url or the content of the image for uri
                    example: http://via.placeholder.com/350x150
    MFA_Challenge_Choices:
      description: Structure of an MFA Challenge of type '?'
      allOf:
        - $ref: '#/components/schemas/MFA_Challenge'
        - type: object
          required:
            - prompt
          properties:
            prompt:
              type: array
              description: An array of choices
              items:
                type: object
                properties:
                  id:
                    type: integer
                    description: The ID of the option (basically the index of the array)
                  category:
                    type: string
                    description: Defines the category to which the value belongs (e.g. Phone, Text, E-mail). It can be null.
                    example: Phone
                  value:
                    type: string
                    description: A phone number or e-mail address. The same value can be present in different categories
                    example: "+1234567890"
